name: sweap 
description: spiral arms
program: train.py
method: bayes
metric:
  name: epoch/val_jaccard
  goal: maximize
parameters:
  loss:
    values: [
      sparse_categorical_crossentropy,
      # dice, 
      # binary_focal_crossentropy
    ]
  dropout_rate:
    distribution: uniform
    min: 0.0
    max: 0.5  
  learning_rate: 
    distribution: uniform
    min: 0.001
    max: 0.01
  batch_size:
    values: [32]
  batch_normalization: 
    values: [False, True]
  kernel_regularization:
    # values: [None, l1, l2, l1_l2]
    values: [None]
  n_filters:
    values: [64, 128]
  min_vote:
    values: [3]
  num_epochs:
    values: [150]
  image_size:
    values: [128]
  mask:
    values: ['spiral_mask']
